"""Remediation write-up and an optional draft pull request.

This is suggest-only on purpose. It does not edit application code. It turns the
real findings (and the grounded AI remediation, when present) into a Markdown
fix guide, and can open that guide as a *draft* pull request for a human to
review and act on. Nothing here merges or changes code on its own.
"""
from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Optional

_ORDER = ["critical", "high", "medium", "low", "info"]


def build_report(results, analysis: Optional[dict] = None) -> str:
    """A Markdown remediation guide built from the real findings only."""
    findings = [f for r in results for f in r.findings]
    remediation = (analysis or {}).get("remediation") or {}
    by_sev: dict[str, list] = {s: [] for s in _ORDER}
    for f in findings:
        by_sev.setdefault(f.severity.value, []).append(f)

    lines = ["# Security remediation guide", "",
             "Generated by Sentari from evidence-backed findings. "
             "Review each item before changing code; this guide suggests fixes, "
             "it does not apply them.", ""]
    total = len(findings)
    lines.append(f"**{total} finding(s).** "
                 + ", ".join(f"{len(by_sev[s])} {s}" for s in _ORDER if by_sev[s]))
    lines.append("")
    for sev in _ORDER:
        items = by_sev.get(sev) or []
        if not items:
            continue
        lines.append(f"## {sev.upper()} ({len(items)})")
        for f in items:
            lines.append(f"### {f.title}")
            if f.location:
                lines.append(f"- **Where:** `{f.location}`")
            lines.append(f"- **What:** {f.description}")
            fix = f.recommendation or remediation.get(getattr(f, 'id', ''), "")
            if fix:
                lines.append(f"- **Fix:** {fix}")
            if f.evidence_ids:
                lines.append(f"- **Evidence:** {', '.join(f.evidence_ids)}")
            lines.append("")
    return "\n".join(lines)


def open_draft_pr(report_md: str, repo_dir: str, target: str,
                  branch: Optional[str] = None,
                  filename: str = "SECURITY_FIXES.md") -> tuple[bool, str]:
    """Write the guide into a repo and open a DRAFT pull request via gh. Graceful."""
    repo = Path(repo_dir)
    if not (repo / ".git").exists():
        return False, f"{repo_dir} is not a git repository"
    from shutil import which
    if not which("gh"):
        return False, "GitHub CLI (gh) not installed; wrote no PR"

    import re
    from datetime import datetime
    slug = re.sub(r"[^A-Za-z0-9._-]", "-", target)[:30]
    branch = branch or f"sentari/fixes-{slug}-{datetime.now():%Y%m%d-%H%M%S}"

    def git(*args):
        return subprocess.run(["git", "-C", str(repo), *args],
                              capture_output=True, text=True)

    try:
        base = git("rev-parse", "--abbrev-ref", "HEAD").stdout.strip() or "main"
        if git("checkout", "-b", branch).returncode != 0:
            return False, f"could not create branch {branch}"
        (repo / filename).write_text(report_md, encoding="utf-8")
        git("add", filename)
        if git("commit", "-m", f"Add Sentari security remediation guide for {target}").returncode != 0:
            git("checkout", base)
            return False, "nothing to commit"
        if git("push", "-u", "origin", branch).returncode != 0:
            git("checkout", base)
            return False, "git push failed (check the remote and credentials)"
        pr = subprocess.run(
            ["gh", "pr", "create", "--draft", "--title",
             f"Security remediation for {target} (Sentari)",
             "--body", "Draft remediation guide from a Sentari assessment. "
                       "Review before merging; no application code was changed.",
             "--head", branch],
            cwd=str(repo), capture_output=True, text=True)
        git("checkout", base)
        if pr.returncode != 0:
            return False, f"gh pr create failed: {pr.stderr.strip()[:200]}"
        return True, f"draft PR opened: {pr.stdout.strip()}"
    except Exception as e:
        return False, f"autofix PR error: {type(e).__name__}: {e}"
